# Creamos los deployments
kubectl create -f src/adservice/deployment/kubernetes-manifests.yaml
kubectl create -f src/cartservice/deployment/kubernetes-manifests.yaml
kubectl create -f src/checkoutservice/deployment/kubernetes-manifests.yaml
kubectl create -f src/currencyservice/deployment/kubernetes-manifests.yaml
kubectl create -f src/emailservice/deployment/kubernetes-manifests.yaml
kubectl create -f src/frontend/deployment/kubernetes-manifests.yaml
kubectl create -f src/loadgenerator/deployment/kubernetes-manifests.yaml
kubectl create -f src/paymentservice/deployment/kubernetes-manifests.yaml
kubectl create -f src/productcatalogservice/deployment/kubernetes-manifests.yaml
kubectl create -f src/recommendationservice/deployment/kubernetes-manifests.yaml
kubectl create -f src/redis/deployment/kubernetes-manifests.yaml
kubectl create -f src/shippingservice/deployment/kubernetes-manifests.yaml